### ISSUE TITLE
Improve error messages.

### ISSUE THREAD

**Issue by elland** [bakkenbaeck/Teapot#15]
cc @marijnschilling 👌🏽

**Comment by marijnschilling** [comment]
The `error.localizedDescription` contains this non-descriptive message shown in the image.
We should have meaningful error messages, and absolute not say anything about `Teapot` in this description. 

![screenshot 2017-10-18 10 06 15](https://user-images.githubusercontent.com/1125417/31707376-6e7eb132-b3ec-11e7-9a65-4090a10ae317.png)
